"use client";

import { useState } from "react";
import Sidebar from '../components/SideBar';
import Header from '../components/Header';

export default function TermsPage() {
  const [activeSection, setActiveSection] = useState('terms');
  const handleLogoClick = () => {
    router.push('/'); // Navigate to the login page when the logo is clicked
  };

  return (
    <div className="min-h-screen flex bg-[url('/bg.png')] bg-cover bg-center">
      {/* Sidebar */}
      <Sidebar activeSection={activeSection} setActiveSection={setActiveSection} />

      {/* Main Content */}
      <div className="flex-grow">
        {/* Header */}
        <Header Name={"Terms and Conditions"} />

        {/* Terms Content Section */}
        <div className="flex justify-center mt-[5rem] sm:mt-[15rem] mx-[2rem] ml-14 sm:ml-14 md:ml-14 lg:ml-16 xl:ml-18"> {/* Add responsive left margin */}
          <div className="bg-gray-200 py-10 px-8 max-w-[1100px] mx-auto text-gray-800 text-center text-lg sm:text-xl md:text-2xl font-medium rounded-lg shadow-lg space-y-4">
            <h2 className="text-2xl font-bold text-[#0077B6] mb-4">Terms and Conditions</h2>
            <p>
              Welcome to HearWise! By accessing or using our platform, you agree to the following terms and conditions. Please read them carefully.
            </p>
            <p>
            HearWise ("we," "us," or "our") respects your privacy and is committed to protecting your personal information. This Privacy Policy outlines how we collect, use, share, and protect your information when you use the HearWise mobile application ("HearWise"). By using HearWise, you agree to the practices described in this Privacy Policy.
            </p>
            <p>
              <strong>1. Information We Collect:</strong> Personal Information: Information that may identify you personally, such as your name, email address, and account login credentials.
Transcription Data: Real-time audio transcriptions generated by the App, which may be saved for your later review.
Usage Data: Information about how you use the App, including in-app settings, preferences, and interaction data, to help us improve the App’s functionality and user experience.
Device and Technical Information: Data such as IP address, device type, operating system, and unique device identifiers, which help us optimize the App’s performance.
            </p>
            <p>
              <strong>2. How We Use Your Information:</strong> We use your information to:

Provide and improve the App’s functionality, including real-time transcription and conversation saving.
Personalize your experience by adjusting settings and preferences according to your usage patterns.
Communicate with you regarding updates, features, or important security information.

            </p>
            <p>
              <strong>3. How We Share Your Information:</strong> We do not sell, trade, or otherwise share your personal information with third parties, except in the following circumstances:

Service Providers: We may share data with third-party service providers who help us operate the App, maintain security, or perform analytics. These parties are bound by confidentiality agreements and are only permitted to use your data as directed by us.
Legal Requirements: We may disclose your information if required by law, to enforce our Terms and Conditions, or to protect the rights, property, or safety of HearWise, our users, or others.

            </p>
            <p>
              <strong>4. Data Security:</strong> We take data security seriously and implement reasonable physical, technical, and administrative safeguards to protect your information from unauthorized access, use, or disclosure. However, please note that no internet-based service is 100% secure, and we cannot guarantee absolute security.

            </p>
            <p>
              <strong>5. Data Retention:</strong> We retain your information only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, or as required by law. You may request that we delete your data at any time by contacting us (see Section 10).
            </p>
            <p>
                <strong>6. Your Rights Under GDPR:</strong>
                If you are located in the European Union, you have certain rights regarding your personal data under the General Data Protection Regulation (GDPR), including:

-Right to Access: You may request access to the personal information we hold about you.
-Right to Rectification: You may request that we correct or update inaccurate or incomplete information.
-Right to Deletion: You may request the deletion of your personal information.
-Right to Restrict Processing: You may request that we restrict the processing of your data under certain conditions.
-Right to Data Portability: You have the right to request that we transfer your data to another organization, where technically feasible.
-Right to Object: You may object to our processing of your data in certain circumstances.
-To exercise any of these rights, please contact us (see Section 10).
                </p>
            <p>
                <strong>7. Children’s Privacy:</strong>
                The App is not intended for use by children under the age of 13, and we do not knowingly collect personal information from children under 13. If we become aware that we have inadvertently collected such data, we will delete it as quickly as possible.

            </p>
            <p>
                <strong>8. Changes to This Privacy Policy:</strong>
                We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal obligations, or other factors. When we make changes, we will update the “Last Updated” date at the top of this page. Your continued use of the App after changes are posted signifies your acceptance of the revised Privacy Policy.


            </p>
            <p>
                <strong>
                9. International Data Transfers:</strong>
                HearWise operates in Romania, and your data may be processed and stored outside of your country of residence. We take steps to ensure that your information receives an adequate level of protection wherever it is processed.
            </p>
            <p>
                <strong>10. Contact Us:
                </strong>
                If you have any questions or concerns regarding this Privacy Policy or wish to exercise any of your data protection rights, please contact us at:
            </p>
            <p><strong>By using HearWise, you acknowledge that you have read, understood, and agree to this Privacy Policy. Thank you for trusting us with your information.</strong></p>

            <h1 className="text-center">Terms and Conditions</h1>
            

            <p><strong>1. Acceptance of Terms:</strong>
            By using HearWise, you agree to comply with and be bound by these Terms. If you do not agree, please do not use the App.</p>

            <p><strong>2. Eligibility:</strong> 
            You must be at least 13 years of age to use the App.</p>

            <p><strong>3. User Responsibilities:</strong> 
            You agree to use HearWise only for lawful purposes and in accordance with these Terms. You will not:</p>
            <ul>
            <li>Violate any applicable laws or regulations.</li>
            <li>Use the App for any unauthorized or illegal purposes.</li>
            <li>Misuse any part of the App, including attempting to hack, overload, or disable it.</li>
            <li>Share or upload content that is abusive, offensive, or infringing upon the rights of others.</li>
            </ul>

            <p><strong>4. Account Management:</strong> 
            To access certain features, you may be required to create an account. You are responsible for maintaining the confidentiality of your account information and password. Please notify us immediately if you suspect any unauthorized use of your account.</p>

            <p><strong>5. Privacy and Data Collection:</strong> 
            HearWise respects your privacy. By using the App, you consent to the collection, use, and disclosure of personal information as outlined in our <a href="/privacy-policy">Privacy Policy</a>. We will only share your data in accordance with this policy.</p>

            <p><strong>6. Content Ownership and License:</strong> 
            All content within the App, including text, images, and logos, is the property of HearWise or its licensors. You are granted a limited, non-exclusive, and non-transferable license to use the App solely for your personal, non-commercial use.</p>

            <p>If you submit content (such as transcriptions or saved conversations), you retain ownership of that content. By submitting content, however, you grant HearWise a worldwide, royalty-free license to use, store, and display this content for the purpose of operating and improving the App.</p>

            <p><strong>7. Termination:</strong> 
            We reserve the right to suspend or terminate your access to the App if you violate these Terms or engage in any activity that is harmful to other users, the App, or our operations.</p>

            <p><strong>8. Limitation of Liability:</strong> 
            To the maximum extent permitted by Romanian law, HearWise will not be liable for any damages, including but not limited to direct, indirect, incidental, or consequential damages, arising out of your use or inability to use the App. This limitation of liability applies even if HearWise has been advised of the possibility of such damages.</p>

            <p><strong>9. Governing Law:</strong> 
            These Terms shall be governed by and construed in accordance with the laws of Romania. Any disputes arising from these Terms or your use of the App shall be subject to the exclusive jurisdiction of the courts of Romania.</p>

            <p><strong>10. Changes to These Terms:</strong> 
            We may update these Terms from time to time. We will notify you of any changes by posting the new Terms on this page. Your continued use of the App after any changes indicates your acceptance of the new Terms.</p>


            <p>By using HearWise, you acknowledge that you have read, understood, and agree to these Terms and Conditions. Thank you for choosing HearWise!</p>

            <p className="text-lg sm:text-xl md:text-2xl font-medium text-center text-gray-800">
              <a className="text-[#101010] font-extrabold text-2xl">Thank you for using </a>
              <a href="/login" className="text-[#0077B6] hover:text-[#238EC7] font-extrabold text-2xl">HearWise</a>!
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
